package com.queen.rxjava2withretrofitdemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.queen.rxjava2withretrofitdemo.greenDaoEntity.User;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.GreenDoubanAvatar;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.GreenDoubanCast;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.GreenDoubanMovieSubject;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.GreenDoubanRating;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.JoinCast;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.JoinDirector;

import com.queen.rxjava2withretrofitdemo.dao.UserDao;
import com.queen.rxjava2withretrofitdemo.dao.GreenDoubanAvatarDao;
import com.queen.rxjava2withretrofitdemo.dao.GreenDoubanCastDao;
import com.queen.rxjava2withretrofitdemo.dao.GreenDoubanMovieSubjectDao;
import com.queen.rxjava2withretrofitdemo.dao.GreenDoubanRatingDao;
import com.queen.rxjava2withretrofitdemo.dao.JoinCastDao;
import com.queen.rxjava2withretrofitdemo.dao.JoinDirectorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig greenDoubanAvatarDaoConfig;
    private final DaoConfig greenDoubanCastDaoConfig;
    private final DaoConfig greenDoubanMovieSubjectDaoConfig;
    private final DaoConfig greenDoubanRatingDaoConfig;
    private final DaoConfig joinCastDaoConfig;
    private final DaoConfig joinDirectorDaoConfig;

    private final UserDao userDao;
    private final GreenDoubanAvatarDao greenDoubanAvatarDao;
    private final GreenDoubanCastDao greenDoubanCastDao;
    private final GreenDoubanMovieSubjectDao greenDoubanMovieSubjectDao;
    private final GreenDoubanRatingDao greenDoubanRatingDao;
    private final JoinCastDao joinCastDao;
    private final JoinDirectorDao joinDirectorDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        greenDoubanAvatarDaoConfig = daoConfigMap.get(GreenDoubanAvatarDao.class).clone();
        greenDoubanAvatarDaoConfig.initIdentityScope(type);

        greenDoubanCastDaoConfig = daoConfigMap.get(GreenDoubanCastDao.class).clone();
        greenDoubanCastDaoConfig.initIdentityScope(type);

        greenDoubanMovieSubjectDaoConfig = daoConfigMap.get(GreenDoubanMovieSubjectDao.class).clone();
        greenDoubanMovieSubjectDaoConfig.initIdentityScope(type);

        greenDoubanRatingDaoConfig = daoConfigMap.get(GreenDoubanRatingDao.class).clone();
        greenDoubanRatingDaoConfig.initIdentityScope(type);

        joinCastDaoConfig = daoConfigMap.get(JoinCastDao.class).clone();
        joinCastDaoConfig.initIdentityScope(type);

        joinDirectorDaoConfig = daoConfigMap.get(JoinDirectorDao.class).clone();
        joinDirectorDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        greenDoubanAvatarDao = new GreenDoubanAvatarDao(greenDoubanAvatarDaoConfig, this);
        greenDoubanCastDao = new GreenDoubanCastDao(greenDoubanCastDaoConfig, this);
        greenDoubanMovieSubjectDao = new GreenDoubanMovieSubjectDao(greenDoubanMovieSubjectDaoConfig, this);
        greenDoubanRatingDao = new GreenDoubanRatingDao(greenDoubanRatingDaoConfig, this);
        joinCastDao = new JoinCastDao(joinCastDaoConfig, this);
        joinDirectorDao = new JoinDirectorDao(joinDirectorDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(GreenDoubanAvatar.class, greenDoubanAvatarDao);
        registerDao(GreenDoubanCast.class, greenDoubanCastDao);
        registerDao(GreenDoubanMovieSubject.class, greenDoubanMovieSubjectDao);
        registerDao(GreenDoubanRating.class, greenDoubanRatingDao);
        registerDao(JoinCast.class, joinCastDao);
        registerDao(JoinDirector.class, joinDirectorDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        greenDoubanAvatarDaoConfig.clearIdentityScope();
        greenDoubanCastDaoConfig.clearIdentityScope();
        greenDoubanMovieSubjectDaoConfig.clearIdentityScope();
        greenDoubanRatingDaoConfig.clearIdentityScope();
        joinCastDaoConfig.clearIdentityScope();
        joinDirectorDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GreenDoubanAvatarDao getGreenDoubanAvatarDao() {
        return greenDoubanAvatarDao;
    }

    public GreenDoubanCastDao getGreenDoubanCastDao() {
        return greenDoubanCastDao;
    }

    public GreenDoubanMovieSubjectDao getGreenDoubanMovieSubjectDao() {
        return greenDoubanMovieSubjectDao;
    }

    public GreenDoubanRatingDao getGreenDoubanRatingDao() {
        return greenDoubanRatingDao;
    }

    public JoinCastDao getJoinCastDao() {
        return joinCastDao;
    }

    public JoinDirectorDao getJoinDirectorDao() {
        return joinDirectorDao;
    }

}
