package com.queen.rxjava2withretrofitdemo.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.queen.rxjava2withretrofitdemo.greenDaoEntity.GreenDoubanAvatar;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.JoinCast;
import com.queen.rxjava2withretrofitdemo.greenDaoEntity.JoinDirector;

import com.queen.rxjava2withretrofitdemo.greenDaoEntity.GreenDoubanCast;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_DOUBAN_CAST".
*/
public class GreenDoubanCastDao extends AbstractDao<GreenDoubanCast, Long> {

    public static final String TABLENAME = "GREEN_DOUBAN_CAST";

    /**
     * Properties of entity GreenDoubanCast.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property GId = new Property(0, Long.class, "gId", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Alt = new Property(3, String.class, "alt", false, "ALT");
        public final static Property DoubanAvatarId = new Property(4, Long.class, "doubanAvatarId", false, "DOUBAN_AVATAR_ID");
    }

    private DaoSession daoSession;

    private Query<GreenDoubanCast> greenDoubanMovieSubject_CastsQuery;
    private Query<GreenDoubanCast> greenDoubanMovieSubject_DirectorsQuery;

    public GreenDoubanCastDao(DaoConfig config) {
        super(config);
    }
    
    public GreenDoubanCastDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_DOUBAN_CAST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: gId
                "\"ID\" TEXT," + // 1: id
                "\"NAME\" TEXT," + // 2: name
                "\"ALT\" TEXT," + // 3: alt
                "\"DOUBAN_AVATAR_ID\" INTEGER);"); // 4: doubanAvatarId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_DOUBAN_CAST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenDoubanCast entity) {
        stmt.clearBindings();
 
        Long gId = entity.getGId();
        if (gId != null) {
            stmt.bindLong(1, gId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String alt = entity.getAlt();
        if (alt != null) {
            stmt.bindString(4, alt);
        }
 
        Long doubanAvatarId = entity.getDoubanAvatarId();
        if (doubanAvatarId != null) {
            stmt.bindLong(5, doubanAvatarId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenDoubanCast entity) {
        stmt.clearBindings();
 
        Long gId = entity.getGId();
        if (gId != null) {
            stmt.bindLong(1, gId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String alt = entity.getAlt();
        if (alt != null) {
            stmt.bindString(4, alt);
        }
 
        Long doubanAvatarId = entity.getDoubanAvatarId();
        if (doubanAvatarId != null) {
            stmt.bindLong(5, doubanAvatarId);
        }
    }

    @Override
    protected final void attachEntity(GreenDoubanCast entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GreenDoubanCast readEntity(Cursor cursor, int offset) {
        GreenDoubanCast entity = new GreenDoubanCast( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // gId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // alt
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // doubanAvatarId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenDoubanCast entity, int offset) {
        entity.setGId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAlt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDoubanAvatarId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GreenDoubanCast entity, long rowId) {
        entity.setGId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GreenDoubanCast entity) {
        if(entity != null) {
            return entity.getGId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GreenDoubanCast entity) {
        return entity.getGId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "casts" to-many relationship of GreenDoubanMovieSubject. */
    public List<GreenDoubanCast> _queryGreenDoubanMovieSubject_Casts(Long subjectId) {
        synchronized (this) {
            if (greenDoubanMovieSubject_CastsQuery == null) {
                QueryBuilder<GreenDoubanCast> queryBuilder = queryBuilder();
                queryBuilder.join(JoinCast.class, JoinCastDao.Properties.CastId)
                    .where(JoinCastDao.Properties.SubjectId.eq(subjectId));
                greenDoubanMovieSubject_CastsQuery = queryBuilder.build();
            }
        }
        Query<GreenDoubanCast> query = greenDoubanMovieSubject_CastsQuery.forCurrentThread();
        query.setParameter(0, subjectId);
        return query.list();
    }

    /** Internal query to resolve the "directors" to-many relationship of GreenDoubanMovieSubject. */
    public List<GreenDoubanCast> _queryGreenDoubanMovieSubject_Directors(Long subjectId) {
        synchronized (this) {
            if (greenDoubanMovieSubject_DirectorsQuery == null) {
                QueryBuilder<GreenDoubanCast> queryBuilder = queryBuilder();
                queryBuilder.join(JoinDirector.class, JoinDirectorDao.Properties.DirectorId)
                    .where(JoinDirectorDao.Properties.SubjectId.eq(subjectId));
                greenDoubanMovieSubject_DirectorsQuery = queryBuilder.build();
            }
        }
        Query<GreenDoubanCast> query = greenDoubanMovieSubject_DirectorsQuery.forCurrentThread();
        query.setParameter(0, subjectId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGreenDoubanAvatarDao().getAllColumns());
            builder.append(" FROM GREEN_DOUBAN_CAST T");
            builder.append(" LEFT JOIN GREEN_DOUBAN_AVATAR T0 ON T.\"DOUBAN_AVATAR_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GreenDoubanCast loadCurrentDeep(Cursor cursor, boolean lock) {
        GreenDoubanCast entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        GreenDoubanAvatar avatars = loadCurrentOther(daoSession.getGreenDoubanAvatarDao(), cursor, offset);
        entity.setAvatars(avatars);

        return entity;    
    }

    public GreenDoubanCast loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GreenDoubanCast> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GreenDoubanCast> list = new ArrayList<GreenDoubanCast>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GreenDoubanCast> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GreenDoubanCast> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
