package com.queen.rxjava2withretrofitdemo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.queen.rxjava2withretrofitdemo.greenDaoEntity.JoinDirector;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_DIRECTOR".
*/
public class JoinDirectorDao extends AbstractDao<JoinDirector, Long> {

    public static final String TABLENAME = "JOIN_DIRECTOR";

    /**
     * Properties of entity JoinDirector.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property GId = new Property(0, Long.class, "gId", true, "_id");
        public final static Property SubjectId = new Property(1, Long.class, "subjectId", false, "SUBJECT_ID");
        public final static Property DirectorId = new Property(2, Long.class, "directorId", false, "DIRECTOR_ID");
    }


    public JoinDirectorDao(DaoConfig config) {
        super(config);
    }
    
    public JoinDirectorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_DIRECTOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: gId
                "\"SUBJECT_ID\" INTEGER," + // 1: subjectId
                "\"DIRECTOR_ID\" INTEGER);"); // 2: directorId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_DIRECTOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinDirector entity) {
        stmt.clearBindings();
 
        Long gId = entity.getGId();
        if (gId != null) {
            stmt.bindLong(1, gId);
        }
 
        Long subjectId = entity.getSubjectId();
        if (subjectId != null) {
            stmt.bindLong(2, subjectId);
        }
 
        Long directorId = entity.getDirectorId();
        if (directorId != null) {
            stmt.bindLong(3, directorId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinDirector entity) {
        stmt.clearBindings();
 
        Long gId = entity.getGId();
        if (gId != null) {
            stmt.bindLong(1, gId);
        }
 
        Long subjectId = entity.getSubjectId();
        if (subjectId != null) {
            stmt.bindLong(2, subjectId);
        }
 
        Long directorId = entity.getDirectorId();
        if (directorId != null) {
            stmt.bindLong(3, directorId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinDirector readEntity(Cursor cursor, int offset) {
        JoinDirector entity = new JoinDirector( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // gId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // subjectId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // directorId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinDirector entity, int offset) {
        entity.setGId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSubjectId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDirectorId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinDirector entity, long rowId) {
        entity.setGId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinDirector entity) {
        if(entity != null) {
            return entity.getGId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinDirector entity) {
        return entity.getGId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
