package com.queen.rxjava2withretrofitdemo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.queen.rxjava2withretrofitdemo.greenDaoEntity.JoinCast;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_CAST".
*/
public class JoinCastDao extends AbstractDao<JoinCast, Long> {

    public static final String TABLENAME = "JOIN_CAST";

    /**
     * Properties of entity JoinCast.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property GId = new Property(0, Long.class, "gId", true, "_id");
        public final static Property SubjectId = new Property(1, Long.class, "subjectId", false, "SUBJECT_ID");
        public final static Property CastId = new Property(2, Long.class, "castId", false, "CAST_ID");
    }


    public JoinCastDao(DaoConfig config) {
        super(config);
    }
    
    public JoinCastDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_CAST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: gId
                "\"SUBJECT_ID\" INTEGER," + // 1: subjectId
                "\"CAST_ID\" INTEGER);"); // 2: castId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_CAST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinCast entity) {
        stmt.clearBindings();
 
        Long gId = entity.getGId();
        if (gId != null) {
            stmt.bindLong(1, gId);
        }
 
        Long subjectId = entity.getSubjectId();
        if (subjectId != null) {
            stmt.bindLong(2, subjectId);
        }
 
        Long castId = entity.getCastId();
        if (castId != null) {
            stmt.bindLong(3, castId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinCast entity) {
        stmt.clearBindings();
 
        Long gId = entity.getGId();
        if (gId != null) {
            stmt.bindLong(1, gId);
        }
 
        Long subjectId = entity.getSubjectId();
        if (subjectId != null) {
            stmt.bindLong(2, subjectId);
        }
 
        Long castId = entity.getCastId();
        if (castId != null) {
            stmt.bindLong(3, castId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinCast readEntity(Cursor cursor, int offset) {
        JoinCast entity = new JoinCast( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // gId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // subjectId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // castId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinCast entity, int offset) {
        entity.setGId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSubjectId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCastId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinCast entity, long rowId) {
        entity.setGId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinCast entity) {
        if(entity != null) {
            return entity.getGId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinCast entity) {
        return entity.getGId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
